site_name: Patashale™
site_url: https://www.patashale.in
site_author: Pranam
site_description: Let's get educated for the present and the future.
theme:
  name: material
  language: en
  favicon: assets/favicon.png
  logo: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections


extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/patashale
      name: Patashale™ on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/patashale
      name: Patashale™ on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/patashale_in
      name: Patashale™ on Twitter
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@patashale
      name: Patashale™ on Mastodon Social
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@patashale
      name: Patashale™ on YouTube

markdown_extensions: 
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Learn: 
    - Home: en/learn.md
    - Law:
        - Indian Penal Code: ipc
        - Constitution of India: coi
    - Software:
        - Redis: learn-redis
        - MongoDB: learn-mongodb
        - Rust: learn-rust
        - Podman: learn-podman
        - OpenStack: learn-openstack
        - Ubuntu: learn-ubuntu
        - MAAS: learn-maas
        - Juju: learn-juju
        - Kubernetes: learn-kubernetes
        - gRPC: learn-grpc
        - GraphQL: learn-graphql
    - Hardware:
        - Arduino: learn-arduino
    - NPO:
        - Section 8: section-eight
  - Products: en/products.md
  - Licenses: en/licenses.md
  - Policies: en/policies.md
  - Security: en/security.md
  - Legal: en/legal.md
  - Team: en/team.md
  - Careers: en/careers.md
  - Contact: en/contact.md
  - Press: en/press.md
  - Store: en/store.md
  - Contribute: en/contribute.md
  - Donate: en/donate.md
  

copyright: Copyright &copy; 2023 <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://www.github.com/patashale">Patashale&#x2122;</a>. All rights reserved.
